### ISSUE TITLE
Storage directory: a suggestion

### ISSUE THREAD

**Issue by kseistrup** [soheilpro/mq#1]
> The items are stored in a directory with the same name that you specify as the queue name. So, be careful to choose a unique name that does not conflict with your existing directories.

How about letting mquere create a queue/spool directory of its own, e.g. `$XDG_DATA_HOME/mqueue` or `~/.local/var/share/mqueue`? Instantly, there will be no more clashes.

Heck, you could even have a `~/.config/mqueue/mqueue.rc`, or similar, that could be sourced at the top of the shell scripts:

```sh
# This is ~/.config/mqueue/mqueue.rc
MQUEUE_QUEUE_DIR=/path/to/mqueue/spool
```

```sh
#!/usr/bin/env sh

QUEUE="$1"

# Ensure queue name
if [[ -z "$QUEUE" ]]; then
  echo 'Usage: echo <message> | mpush <queue>'
  exit 1
fi

test -z "$MQUEUE_QUEUE_DIR" && {
  test -r ~/.config/mqueue/mqueue.rc \
  && source ~/.config/mqueue/mqueue.rc
}

[…]
```

If you plan on having other variables in `mqueue.rc`, you obviously need another approach so that user-set variables do not get overwritten, but conceptually.

**Comment by soheilpro** [comment]
Thanks for the suggestion. I could do that but this was a small project and I wanted to keep it simple.
